### PR TITLE
add release

### PR DESCRIPTION
**Pull request by Rouzip**
Add release function to the operation struct, to release the async queue from the file.

### CODE REVIEW

**Comment by d0u9** [comment]
I can't find `async_notify()` in the kernel source tree 4.9. Is this a typo?

Also, please obey the coding-style of kernel C code. You can find it [HERE](https://elixir.bootlin.com/linux/latest/source/Documentation/process/coding-style.rst). Tab should  be 8 spaces width other than 4 spaces. The brace `{` should be placed at the end of line, not the begging of next line.

**Comment by Rouzip** [comment]
Sorry for my wrong commit, I renamed the notify function and forget that :(

**Comment by d0u9** [comment]
Sorry, I still can't find `async_notify_fasync()` in kernel tree.

**Comment by Rouzip** [comment]
It is your notify funciton, and different params can release the async_queue.
``` 
    int async_notify_fasync(int fd, struct file *filp, int mode)
{
	struct async_notify_dev *dev = filp->private_data;


	return fasync_helper(fd, filp, mode, &dev->async_queue);
}

**Comment by d0u9** [comment]
Sorry for my foolishness. 

I suggest to rename `async_release()` to ` async_notify_release()` to keep name convention consistent. 

Also, please do not call `async_notify_fasync()` directly inside `async_release()`, this leads to unclear. I think it is good to rewrite `async_release()`, which has same content as `async_notify_fasync()`. 

Thank you for your great work.

**Comment by Rouzip** [comment]
Ok, I have fixed the name style as you suggested.

**Pull request merged**
